Enum refactor
takakia/lovok pull request #85
Opened 2022-11-30 21:57 UTC by smiller1212

Renamed and reordered status code enums. Sets initial status before box parsing to be UNKOWN_BOX, instead of VALID_FILE. 

Resolves #70 
Resolves #71

2022-11-30 22:01 UTC, a-molis requested changes

2022-11-30 22:01 UTC, a-molis commented on src/boxes/file_level_boxes.cpp
> +            std::cout << "Unknown box name in ParseMoov: ";
Can you change these so they are not referencing the function name? Could this read like `Encountered unknown box when parsing moov box`

2022-11-30 22:21 UTC, a-molis approved these changes
This looks good to me

2022-12-01 23:00 UTC, Yamack approved these changes

2022-12-01 23:00 UTC, merged